spring:
  application:
    name: heima-ai
  ai:
    deepseek:
      api-key:
      api-base-url: https://api.deepseek.com
      timeout: 30s
      chat:
        options:
          model: deepseek-chat
          temperature: 0.8