spring:
  application:
    name: heima-ai
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.8

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
    com.itheima.ai: DEBUG